# Generated by Django 4.1.3 on 2022-11-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profileimg",
            field=models.ImageField(default="logo.png", upload_to="profile_images"),
        ),
    ]
